import type { Language } from '../i18n/translations'

const finalMoveTranslations: Array<[RegExp, string]> = [
  [/\bTRAMPA ROCAS\b/gi, 'Stealth Rock'],
  [/\bTrampa Rocas\b/gi, 'Stealth Rock'],
  [/\bOTRA VEZ\b/gi, 'Encore'],
  [/\bOtra Vez\b/gi, 'Encore'],
  [/\bOtra vez\b/gi, 'Encore'],
  [/\bMaquinaci[oó]n\b/gi, 'Nasty Plot'],
  [/\bTambor\b/gi, 'Belly Drum'],
  [/\bDanza Aleteo\b/gi, 'Quiver Dance'],
  [/\bDanza Espada\b/gi, 'Swords Dance'],
  [/\bDanza Drag[oó]n\b/gi, 'Dragon Dance'],
  [/\bVelocidad X\b/gi, 'X Speed'],
  [/\bPrecisi[oó]n X\b/gi, 'X Accuracy'],
  [/\bEspecial X\b/gi, 'X Sp. Atk'],
  [/\bAtaque X\b/gi, 'X Attack'],
  [/\bDefensa X\b/gi, 'X Defense'],
  [/\bProtecci[oó]n\b/gi, 'Protect'],
  [/\bBostezo\b/gi, 'Yawn'],
  [/\bAmortiguador\b/gi, 'Soft-Boiled'],
  [/\bTeletransporte\b/gi, 'Teleport'],
  [/\bEncanto\b/gi, 'Charm'],
  [/\bT[oó]xico\b/gi, 'Toxic'],
  [/\bOnda Trueno\b/gi, 'Thunder Wave'],
  [/\bSustituto\b/gi, 'Substitute'],
  [/\bRespiro\b/gi, 'Roost'],
  [/\bRecuperaci[oó]n\b/gi, 'Recover'],
  [/\bDescanso\b/gi, 'Rest'],
  [/\bSurf\b/gi, 'Surf'],
  [/\bCascada\b/gi, 'Waterfall'],
  [/\bAcua Cola\b/gi, 'Aqua Tail'],
  [/\bHidrobomba\b/gi, 'Hydro Pump'],
  [/\bEscaldar\b/gi, 'Scald'],
  [/\bRayo Hielo\b/gi, 'Ice Beam'],
  [/\bRayo\b/gi, 'Thunderbolt'],
  [/\bTrueno\b/gi, 'Thunder'],
  [/\bLanzallamas\b/gi, 'Flamethrower'],
  [/\bLlamarada\b/gi, 'Fire Blast'],
  [/\bSofoco\b/gi, 'Overheat'],
  [/\bPs[ií]quico\b/gi, 'Psychic'],
  [/\bPsicocarga\b/gi, 'Psyshock'],
  [/\bBola Sombra\b/gi, 'Shadow Ball'],
  [/\bPulso Umbr[ií]o\b/gi, 'Dark Pulse'],
  [/\bPulso Drag[oó]n\b/gi, 'Dragon Pulse'],
  [/\bCometa Draco\b/gi, 'Draco Meteor'],
  [/\bGarra Drag[oó]n\b/gi, 'Dragon Claw'],
  [/\bEnfado\b/gi, 'Outrage'],
  [/\bEnergibola\b/gi, 'Energy Ball'],
  [/\bGigadrenado\b/gi, 'Giga Drain'],
  [/\bHierba Lazo\b/gi, 'Grass Knot'],
  [/\bOnda Certera\b/gi, 'Focus Blast'],
  [/\bA Bocajarro\b/gi, 'Close Combat'],
  [/\bFuerza Bruta\b/gi, 'Superpower'],
  [/\bVoltio Cruel\b/gi, 'Wild Charge'],
  [/\bAcr[oó]bata\b/gi, 'Acrobatics'],
  [/\bPuño Drenaje\b/gi, 'Drain Punch'],
  [/\bPuño Trueno\b/gi, 'Thunder Punch'],
  [/\bPuño Hielo\b/gi, 'Ice Punch'],
  [/\bPuño Fuego\b/gi, 'Fire Punch'],
  [/\bPatada Salto Alta\b/gi, 'High Jump Kick'],
  [/\bGolpe Bajo\b/gi, 'Sucker Punch'],
  [/\bTriturar\b/gi, 'Crunch'],
  [/\bRoca Afilada\b/gi, 'Stone Edge'],
  [/\bAvalancha\b/gi, 'Rock Slide'],
  [/\bTerremoto\b/gi, 'Earthquake'],
  [/\bCabezazo Zen\b/gi, 'Zen Headbutt'],
  [/\bGiro Bola\b/gi, 'Gyro Ball'],
  [/\bAutodestrucci[oó]n\b/gi, 'Self-Destruct'],
  [/\bExplosi[oó]n\b/gi, 'Explosion'],
  [/\bHuesomerang\b/gi, 'Bonemerang'],
  [/\bPoder Oculto\b/gi, 'Hidden Power'],
  [/\bBomba Lodo\b/gi, 'Sludge Bomb'],
]

const finalItemTranslations: Array<[RegExp, string]> = [
  [/\bLlamasfera\b/gi, 'Flame Orb'],
  [/\bVidasfera\b/gi, 'Life Orb'],
  [/\bBanda Focus\b/gi, 'Focus Sash'],
  [/\bRestos\b/gi, 'Leftovers'],
  [/\bBaya Zidra\b/gi, 'Sitrus Berry'],
  [/\bHierba Blanca\b/gi, 'White Herb'],
  [/\bRevivir Hierba\b/gi, 'Revival Herb'],
  [/\bMedicina Pequeña\b/gi, 'Small Medicine'],
  [/\bMax Poci[oó]n\b/gi, 'Max Potion'],
]

const finalAbilityTranslations: Array<[RegExp, string]> = [
  [/\bPiel Seca\b/gi, 'Dry Skin'],
  [/\bAbsorbe Agua\b/gi, 'Water Absorb'],
  [/\bLevitaci[oó]n\b/gi, 'Levitate'],
]

const finalPhraseTranslations: Array<[RegExp, string]> = [
  [/\bRuta r[aá]pida\b/gi, 'Fast route'],
  [/\bRuta estable\b/gi, 'Stable route'],
  [/\bRuta segura\b/gi, 'Safe route'],
  [/\bRuta ahorro\b/gi, 'Budget route'],
  [/\bRuta RNG\b/gi, 'RNG route'],
  [/\bVarias opciones\b/gi, 'Multiple options'],
  [/\bNo cambia\b/g, 'Does not switch'],
  [/\bNO CAMBIA\b/g, 'DOES NOT SWITCH'],
  [/\bSi utiliza\b/gi, 'If it uses'],
  [/\bSi usa\b/gi, 'If it uses'],
  [/\bSi cambia a\b/gi, 'If it switches to'],
  [/\bSi entra\b/gi, 'If it comes in'],
  [/\bSi sale\b/gi, 'If it comes in'],
  [/\bCuando salga\b/gi, 'When it comes in'],
  [/\bSi tiene\b/gi, 'If it has'],
  [/\bSi no tiene\b/gi, 'If it does not have'],
  [/\bCambia a\b/g, 'Switch to'],
  [/\bcambia a\b/gi, 'switch to'],
  [/\bEntra con\b/g, 'Bring in'],
  [/\bentra con\b/gi, 'bring in'],
  [/\bEntra\b/g, 'Bring in'],
  [/\bentra\b/gi, 'bring in'],
  [/\bSaca a\b/g, 'Send in'],
  [/\bsaca a\b/gi, 'send in'],
  [/\bColoca\b/g, 'Set up'],
  [/\bcoloca\b/gi, 'set up'],
  [/\bUsa\b/g, 'Use'],
  [/\busa\b/gi, 'use'],
  [/\bUtiliza\b/g, 'Use'],
  [/\butiliza\b/gi, 'use'],
  [/\bMant[eé]n\b/g, 'Keep'],
  [/\bmant[eé]n\b/gi, 'keep'],
  [/\bFrente a\b/g, 'Against'],
  [/\bfrente a\b/gi, 'against'],
  [/\bContra\b/g, 'Against'],
  [/\bcontra\b/gi, 'against'],
  [/\bpara quedar en\b/gi, 'to reach'],
  [/\bhasta quedar en\b/gi, 'to reach'],
  [/\bhasta \+([0-9]+) Ataque Especial\b/gi, 'to +$1 Special Attack'],
  [/\bhasta \+([0-9]+) Ataque\b/gi, 'to +$1 Attack'],
  [/\bhasta \+([0-9]+) Velocidad\b/gi, 'to +$1 Speed'],
  [/\bAtaque Especial\b/gi, 'Special Attack'],
  [/\bDefensa Especial\b/gi, 'Special Defense'],
  [/\bAtaque\b/gi, 'Attack'],
  [/\bDefensa\b/gi, 'Defense'],
  [/\bVelocidad\b/gi, 'Speed'],
  [/\bPrecisi[oó]n\b/gi, 'Accuracy'],
  [/\bPS al m[aá]ximo\b/gi, 'full HP'],
  [/\bPS\b/g, 'HP'],
  [/\bbarre\b/gi, 'sweep'],
  [/\bbarrer\b/gi, 'sweep'],
  [/\bdebilita a\b/gi, 'knocks out'],
  [/\bqueda debilitado\b/gi, 'gets knocked out'],
  [/\bqueda debilitada\b/gi, 'gets knocked out'],
  [/\bse debilita\b/gi, 'gets knocked out'],
  [/\btipo Tierra\b/gi, 'Ground-type'],
  [/\btipo Agua\b/gi, 'Water-type'],
  [/\btipo Fuego\b/gi, 'Fire-type'],
  [/\btipo Ps[ií]quico\b/gi, 'Psychic-type'],
  [/\btipo Fantasma\b/gi, 'Ghost-type'],
  [/\btipo Drag[oó]n\b/gi, 'Dragon-type'],
  [/\bataques s[uú]per efectivos\b/gi, 'super-effective attacks'],
  [/\brival\b/gi, 'opponent'],
  [/\bobjeto\b/gi, 'item'],
  [/\bmovimiento\b/gi, 'move'],
  [/\bamenaza\b/gi, 'threat'],
  [/\bcampo\b/gi, 'field'],
  [/\bTeselia\b/g, 'Unova'],
]

const pivotCleanup: Array<[RegExp, string]> = [
  [/\b[Ss]acrifice ([A-Z][A-Za-z0-9♀♂'’.-]+) and bring in/g, '$1 enters as a pivot, then bring in'],
  [/\b[Ss]acrifice ([A-Z][A-Za-z0-9♀♂'’.-]+) to take/g, '$1 enters as a pivot to take'],
  [/\b[Ss]acrifice ([A-Z][A-Za-z0-9♀♂'’.-]+)/g, '$1 enters as a pivot'],
  [/\b[Ss]end in ([A-Z][A-Za-z0-9♀♂'’.-]+) as a pivot and bring in/g, 'Send in $1 as a pivot, then bring in'],
  [/\bsend in ([A-Z][A-Za-z0-9♀♂'’.-]+) as a pivot and bring in/g, 'send in $1 as a pivot, then bring in'],
  [/\b[Ss]end in ([A-Z][A-Za-z0-9♀♂'’.-]+) and use it as a pivot/g, 'Send in $1 as a pivot'],
  [/\bsend in ([A-Z][A-Za-z0-9♀♂'’.-]+) and use it as a pivot/g, 'send in $1 as a pivot'],
  [/\b[Ll]et ([A-Z][A-Za-z0-9♀♂'’.-]+) faint/g, '$1 enters as a pivot'],
  [/\blet it faint so ([A-Z][A-Za-z0-9♀♂'’.-]+) can enter safely/g, 'use it as a pivot so $1 can enter safely'],
  [/\blet it faint/g, 'use it as a pivot'],
  [/\bdeja que ([A-Z][A-Za-z0-9♀♂'’.-]+) quede debilitado\b/gi, '$1 enters as a pivot'],
  [/\bdeja que ([A-Z][A-Za-z0-9♀♂'’.-]+) caiga\b/gi, '$1 enters as a pivot'],
]

const grammarCleanup: Array<[RegExp, string]> = [
  [/\bUse Nasty Plot until \+([0-9]+)/g, 'Use Nasty Plot to +$1'],
  [/\buse Nasty Plot until \+([0-9]+)/g, 'use Nasty Plot to +$1'],
  [/\bUse Belly Drum until \+6 Attack/g, 'Use Belly Drum to reach +6 Attack'],
  [/\buse Belly Drum until \+6 Attack/g, 'use Belly Drum to reach +6 Attack'],
  [/\bUse Quiver Dance x([0-9]+)/g, 'Use Quiver Dance x$1'],
  [/\buse Quiver Dance x([0-9]+)/g, 'use Quiver Dance x$1'],
  [/\bto reach \+([0-9]+) Speed Speed\b/g, 'to reach +$1 Speed'],
  [/\bto reach \+([0-9]+) Attack Attack\b/g, 'to reach +$1 Attack'],
  [/\bto reach \+([0-9]+) Special Attack Special Attack\b/g, 'to reach +$1 Special Attack'],
  [/\bbring in with\b/gi, 'bring in'],
  [/\bBring in with\b/g, 'Bring in'],
  [/\bSwitch to with\b/g, 'Switch to'],
  [/\bswitch to with\b/gi, 'switch to'],
  [/\bUse use\b/g, 'Use'],
  [/\buse use\b/g, 'use'],
  [/\bThen then\b/g, 'Then'],
  [/\bthen then\b/g, 'then'],
  [/\s+([.,:;])/g, '$1'],
]

export const cleanEnglishStrategyText = (text: string, language: Language) => {
  if (language === 'es') return text

  return [
    ...finalMoveTranslations,
    ...finalItemTranslations,
    ...finalAbilityTranslations,
    ...finalPhraseTranslations,
    ...pivotCleanup,
    ...grammarCleanup,
  ].reduce((currentText, [pattern, replacement]) => currentText.replace(pattern, replacement), text)
}
