import type { Language } from '../i18n/translations'

const finalMoveTranslations: Array<[RegExp, string]> = [
  [/\bTRUCO\b/gi, 'Trick'],
  [/\bTruco\b/gi, 'Trick'],
  [/\bTRAMPA ROCAS\b/gi, 'Stealth Rock'],
  [/\bTrampa Rocas\b/gi, 'Stealth Rock'],
  [/\bOTRA VEZ\b/gi, 'Encore'],
  [/\bOtra Vez\b/gi, 'Encore'],
  [/\bOtra vez\b/gi, 'Encore'],
  [/\bMaquinaci[oó]n\b/gi, 'Nasty Plot'],
  [/\bTambor\b/gi, 'Belly Drum'],
  [/\bDanza Aleteo\b/gi, 'Quiver Dance'],
  [/\bDanza Espada\b/gi, 'Swords Dance'],
  [/\bDanza Drag[oó]n\b/gi, 'Dragon Dance'],
  [/\bDanza Llama\b/gi, 'Fiery Dance'],
  [/\bDanza Lluvia\b/gi, 'Rain Dance'],
  [/\bD[ií]a Soleado\b/gi, 'Sunny Day'],
  [/\bPaz Mental\b/gi, 'Calm Mind'],
  [/\bCorpulentia\b/gi, 'Bulk Up'],
  [/\bMaldici[oó]n\b/gi, 'Curse'],
  [/\bVelocidad X\b/gi, 'X Speed'],
  [/\bPrecisi[oó]n X\b/gi, 'X Accuracy'],
  [/\bEspecial X\b/gi, 'X Sp. Atk'],
  [/\bAtaque X\b/gi, 'X Attack'],
  [/\bDefensa X\b/gi, 'X Defense'],
  [/\bProtecci[oó]n\b/gi, 'Protect'],
  [/\bBostezo\b/gi, 'Yawn'],
  [/\bAmortiguador\b/gi, 'Soft-Boiled'],
  [/\bTeletransporte\b/gi, 'Teleport'],
  [/\bEncanto\b/gi, 'Charm'],
  [/\bT[oó]xico\b/gi, 'Toxic'],
  [/\bOnda Trueno\b/gi, 'Thunder Wave'],
  [/\bSustituto\b/gi, 'Substitute'],
  [/\bRespiro\b/gi, 'Roost'],
  [/\bRecuperaci[oó]n\b/gi, 'Recover'],
  [/\bDescanso\b/gi, 'Rest'],
  [/\bReflejo\b/gi, 'Reflect'],
  [/\bPantalla Luz\b/gi, 'Light Screen'],
  [/\bP[uú]as T[oó]xicas\b/gi, 'Toxic Spikes'],
  [/\bP[uú]as\b/gi, 'Spikes'],
  [/\bSurf\b/gi, 'Surf'],
  [/\bCascada\b/gi, 'Waterfall'],
  [/\bAcua Cola\b/gi, 'Aqua Tail'],
  [/\bHidrobomba\b/gi, 'Hydro Pump'],
  [/\bEscaldar\b/gi, 'Scald'],
  [/\bRayo Hielo\b/gi, 'Ice Beam'],
  [/\bViento Hielo\b/gi, 'Icy Wind'],
  [/\bCar[aá]mbano\b/gi, 'Icicle Spear'],
  [/\bCanto Helado\b/gi, 'Ice Shard'],
  [/\bRayo\b/gi, 'Thunderbolt'],
  [/\bTrueno\b/gi, 'Thunder'],
  [/\bChispazo\b/gi, 'Discharge'],
  [/\bVoltiocambio\b/gi, 'Volt Switch'],
  [/\bLanzallamas\b/gi, 'Flamethrower'],
  [/\bLlamarada\b/gi, 'Fire Blast'],
  [/\bSofoco\b/gi, 'Overheat'],
  [/\bEnvite [IÍ]gneo\b/gi, 'Flare Blitz'],
  [/\bPs[ií]quico\b/gi, 'Psychic'],
  [/\bPsicocarga\b/gi, 'Psyshock'],
  [/\bBola Sombra\b/gi, 'Shadow Ball'],
  [/\bPulso Umbr[ií]o\b/gi, 'Dark Pulse'],
  [/\bTajo Umbr[ií]o\b/gi, 'Night Slash'],
  [/\bPulso Drag[oó]n\b/gi, 'Dragon Pulse'],
  [/\bCometa Draco\b/gi, 'Draco Meteor'],
  [/\bGarra Drag[oó]n\b/gi, 'Dragon Claw'],
  [/\bEnfado\b/gi, 'Outrage'],
  [/\bEnergibola\b/gi, 'Energy Ball'],
  [/\bGigadrenado\b/gi, 'Giga Drain'],
  [/\bHierba Lazo\b/gi, 'Grass Knot'],
  [/\bLluevehojas\b/gi, 'Leaf Storm'],
  [/\bBomba Germen\b/gi, 'Seed Bomb'],
  [/\bOnda Certera\b/gi, 'Focus Blast'],
  [/\bA Bocajarro\b/gi, 'Close Combat'],
  [/\bFuerza Bruta\b/gi, 'Superpower'],
  [/\bVoltio Cruel\b/gi, 'Wild Charge'],
  [/\bAcr[oó]bata\b/gi, 'Acrobatics'],
  [/\bGolpe A[eé]reo\b/gi, 'Aerial Ace'],
  [/\bTajo A[eé]reo\b/gi, 'Air Slash'],
  [/\bP[aá]jaro Osado\b/gi, 'Brave Bird'],
  [/\bVendaval\b/gi, 'Hurricane'],
  [/\bPuño Drenaje\b/gi, 'Drain Punch'],
  [/\bPuño Trueno\b/gi, 'Thunder Punch'],
  [/\bPuño Hielo\b/gi, 'Ice Punch'],
  [/\bPuño Fuego\b/gi, 'Fire Punch'],
  [/\bPuño Bala\b/gi, 'Bullet Punch'],
  [/\bPatada Salto Alta\b/gi, 'High Jump Kick'],
  [/\bGolpe Bajo\b/gi, 'Sucker Punch'],
  [/\bTriturar\b/gi, 'Crunch'],
  [/\bDesarme\b/gi, 'Knock Off'],
  [/\bImagen\b/gi, 'Facade'],
  [/\bRoca Afilada\b/gi, 'Stone Edge'],
  [/\bAvalancha\b/gi, 'Rock Slide'],
  [/\bTerremoto\b/gi, 'Earthquake'],
  [/\bTierra Viva\b/gi, 'Earth Power'],
  [/\bCabezazo Zen\b/gi, 'Zen Headbutt'],
  [/\bGiro Bola\b/gi, 'Gyro Ball'],
  [/\bAutodestrucci[oó]n\b/gi, 'Self-Destruct'],
  [/\bExplosi[oó]n\b/gi, 'Explosion'],
  [/\bHuesomerang\b/gi, 'Bonemerang'],
  [/\bPoder Oculto\b/gi, 'Hidden Power'],
  [/\bBomba Lodo\b/gi, 'Sludge Bomb'],
  [/\bPuya Nociva\b/gi, 'Poison Jab'],
  [/\bBrillo M[aá]gico\b/gi, 'Dazzling Gleam'],
  [/\bFuerza Lunar\b/gi, 'Moonblast'],
  [/\bVelocidad Extrema\b/gi, 'Extreme Speed'],
  [/\bAtaque R[aá]pido\b/gi, 'Quick Attack'],
  [/\bIda y Vuelta\b/gi, 'U-turn'],
]

const finalItemTranslations: Array<[RegExp, string]> = [
  [/\bLlamasfera\b/gi, 'Flame Orb'],
  [/\bVidasfera\b/gi, 'Life Orb'],
  [/\bBanda Focus\b/gi, 'Focus Sash'],
  [/\bRestos\b/gi, 'Leftovers'],
  [/\bBaya Zidra\b/gi, 'Sitrus Berry'],
  [/\bBaya Ziuela\b/gi, 'Lum Berry'],
  [/\bBaya Aranja\b/gi, 'Oran Berry'],
  [/\bHierba Blanca\b/gi, 'White Herb'],
  [/\bRevivir Hierba\b/gi, 'Revival Herb'],
  [/\bMedicina Pequeña\b/gi, 'Small Medicine'],
  [/\bMax Poci[oó]n\b/gi, 'Max Potion'],
  [/\bPañuelo Elegido\b/gi, 'Choice Scarf'],
  [/\bCinta Elegida\b/gi, 'Choice Band'],
  [/\bGafas Elegidas\b/gi, 'Choice Specs'],
]

const finalAbilityTranslations: Array<[RegExp, string]> = [
  [/\bPiel Seca\b/gi, 'Dry Skin'],
  [/\bAbsorbe Agua\b/gi, 'Water Absorb'],
  [/\bAbsorbe Electricidad\b/gi, 'Volt Absorb'],
  [/\bPararrayos\b/gi, 'Lightning Rod'],
  [/\bLevitaci[oó]n\b/gi, 'Levitate'],
  [/\bIntimidaci[oó]n\b/gi, 'Intimidate'],
  [/\bRobustez\b/gi, 'Sturdy'],
  [/\bAgallas\b/gi, 'Guts'],
  [/\bImpulso\b/gi, 'Speed Boost'],
]

const finalPhraseTranslations: Array<[RegExp, string]> = [
  [/\bRuta r[aá]pida\b/gi, 'Fast route'],
  [/\bRuta estable\b/gi, 'Stable route'],
  [/\bRuta segura\b/gi, 'Safe route'],
  [/\bRuta ahorro\b/gi, 'Budget route'],
  [/\bRuta alternativa\b/gi, 'Alternative route'],
  [/\bRuta RNG\b/gi, 'RNG route'],
  [/\bruta recomendada\b/gi, 'recommended route'],
  [/\bruta principal\b/gi, 'main route'],
  [/\bruta\b/gi, 'route'],
  [/\brutas\b/gi, 'routes'],
  [/\bVarias opciones\b/gi, 'Multiple options'],
  [/\bopciones\b/gi, 'options'],
  [/\bopci[oó]n\b/gi, 'option'],
  [/\bNo cambia\b/g, 'Does not switch'],
  [/\bNO CAMBIA\b/g, 'DOES NOT SWITCH'],
  [/\bSi después entra\b/gi, 'If it comes in after that'],
  [/\bSi luego entra\b/gi, 'If it comes in after that'],
  [/\bSi utiliza\b/gi, 'If it uses'],
  [/\bSi usa\b/gi, 'If it uses'],
  [/\bSi cambia a\b/gi, 'If it switches to'],
  [/\bSi entra\b/gi, 'If it comes in'],
  [/\bSi sale\b/gi, 'If it comes in'],
  [/\bCuando vuelva\b/gi, 'When it comes back'],
  [/\bCuando entre\b/gi, 'When it comes in'],
  [/\bCuando entra\b/gi, 'When it comes in'],
  [/\bCuando salga\b/gi, 'When it comes in'],
  [/\bCuando sale\b/gi, 'When it comes in'],
  [/\bCuando\b/g, 'When'],
  [/\bcuando\b/gi, 'when'],
  [/\bSi tiene\b/gi, 'If it has'],
  [/\bSi no tiene\b/gi, 'If it does not have'],
  [/\bSi quieres ahorrar dinero\b/gi, 'If you want to save money'],
  [/\bahorrar dinero\b/gi, 'save money'],
  [/\bahorro\b/gi, 'budget'],
  [/\bCambia a\b/g, 'Switch to'],
  [/\bcambia a\b/gi, 'switch to'],
  [/\bcambia\b/gi, 'switch'],
  [/\bcambiar\b/gi, 'switch'],
  [/\bcambie\b/gi, 'switches'],
  [/\bEntra con\b/g, 'Bring in'],
  [/\bentra con\b/gi, 'bring in'],
  [/\bEntra\b/g, 'Bring in'],
  [/\bentra\b/gi, 'bring in'],
  [/\bSaca a\b/g, 'Send in'],
  [/\bsaca a\b/gi, 'send in'],
  [/\bEnv[ií]a a\b/g, 'Send in'],
  [/\benv[ií]a a\b/gi, 'send in'],
  [/\bColoca\b/g, 'Set up'],
  [/\bcoloca\b/gi, 'set up'],
  [/\bUsa\b/g, 'Use'],
  [/\busa\b/gi, 'use'],
  [/\bUtiliza\b/g, 'Use'],
  [/\butiliza\b/gi, 'use'],
  [/\bMant[eé]n\b/g, 'Keep'],
  [/\bmant[eé]n\b/gi, 'keep'],
  [/\bmantener a\b/gi, 'keep'],
  [/\bFrente a\b/g, 'Against'],
  [/\bfrente a\b/gi, 'against'],
  [/\bContra\b/g, 'Against'],
  [/\bcontra\b/gi, 'against'],
  [/\bCon ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/g, 'With $1'],
  [/\bcon ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/g, 'with $1'],
  [/\bLuego\b/g, 'Then'],
  [/\bluego\b/gi, 'then'],
  [/\bDespués de\b/g, 'After'],
  [/\bdespués de\b/gi, 'after'],
  [/\bDespués\b/g, 'Then'],
  [/\bdespués\b/gi, 'then'],
  [/\bluego de\b/gi, 'after'],
  [/\by luego\b/gi, 'and then'],
  [/\bpara quedar en\b/gi, 'to reach'],
  [/\bhasta quedar en\b/gi, 'to reach'],
  [/\bpara quedar\b/gi, 'to reach'],
  [/\bquedar con\b/gi, 'be at'],
  [/\bquedar\b/gi, 'reach'],
  [/\bhasta \+([0-9]+) Ataque Especial\b/gi, 'to +$1 Special Attack'],
  [/\bhasta \+([0-9]+) Ataque\b/gi, 'to +$1 Attack'],
  [/\bhasta \+([0-9]+) Velocidad\b/gi, 'to +$1 Speed'],
  [/\bAtaque Especial\b/gi, 'Special Attack'],
  [/\bDefensa Especial\b/gi, 'Special Defense'],
  [/\bAtaque\b/gi, 'Attack'],
  [/\bDefensa\b/gi, 'Defense'],
  [/\bVelocidad\b/gi, 'Speed'],
  [/\bPrecisi[oó]n\b/gi, 'Accuracy'],
  [/\bPS al m[aá]ximo\b/gi, 'full HP'],
  [/\blos PS al m[aá]ximo\b/gi, 'full HP'],
  [/\bPS\b/g, 'HP'],
  [/\bbarre\b/gi, 'sweep'],
  [/\bbarrer\b/gi, 'sweep'],
  [/\bdebilita a\b/gi, 'knocks out'],
  [/\bdebilite a\b/gi, 'knocks out'],
  [/\bqueda debilitado\b/gi, 'gets knocked out'],
  [/\bqueda debilitada\b/gi, 'gets knocked out'],
  [/\bse debilita\b/gi, 'gets knocked out'],
  [/\bdebilitado\b/gi, 'knocked out'],
  [/\bdebilitada\b/gi, 'knocked out'],
  [/\bderr[oó]talo\b/gi, 'knock it out'],
  [/\bderrota a\b/gi, 'knock out'],
  [/\btermina con\b/gi, 'finish with'],
  [/\bcomienza a\b/gi, 'start'],
  [/\bcontin[uú]a la ruta\b/gi, 'continue the route'],
  [/\bcontin[uú]a\b/gi, 'continue'],
  [/\bsigue atacando\b/gi, 'keep attacking'],
  [/\bsigue la ruta\b/gi, 'follow the route'],
  [/\bsigue\b/gi, 'continue'],
  [/\brevisa su movimiento\b/gi, 'check its move'],
  [/\brevisa su objeto\b/gi, 'check its item'],
  [/\brevisa\b/gi, 'check'],
  [/\bespera a\b/gi, 'wait for'],
  [/\bantes de decidir\b/gi, 'before deciding'],
  [/\bantes de elegir la route\b/gi, 'before choosing the route'],
  [/\bseg[uú]n su item\b/gi, 'based on its item'],
  [/\bbasado en su item\b/gi, 'based on its item'],
  [/\bdirectamente\b/gi, 'directly'],
  [/\bcada vez que puedas\b/gi, 'whenever possible'],
  [/\best[eé] listo\b/gi, 'is ready'],
  [/\bcontrolar al opponent\b/gi, 'control the opponent'],
  [/\bse queda en el field\b/gi, 'stays on the field'],
  [/\bse queda en field\b/gi, 'stays on the field'],
  [/\bse queda\b/gi, 'stays in'],
  [/\bqueda en field\b/gi, 'stays on the field'],
  [/\ben el field\b/gi, 'on the field'],
  [/\ben field\b/gi, 'on the field'],
  [/\bal field\b/gi, 'to the field'],
  [/\bcampo\b/gi, 'field'],
  [/\bencerrado\b/gi, 'locked in'],
  [/\bencerrada\b/gi, 'locked in'],
  [/\bbloqueado\b/gi, 'locked'],
  [/\bbloqueada\b/gi, 'locked'],
  [/\bsube con\b/gi, 'boost with'],
  [/\bcurarte\b/gi, 'healing'],
  [/\bcurarte\b/gi, 'heal'],
  [/\bse quema\b/gi, 'gets burned'],
  [/\bpuedes\b/gi, 'you can'],
  [/\ba[uú]n\b/gi, 'still'],
  [/\bsorpresivamente\b/gi, 'unexpectedly'],
  [/\bcr[ií]tico\b/gi, 'critical hit'],
  [/\bcritico\b/gi, 'critical hit'],
  [/\bataque Ps[ií]quico\b/gi, 'Psychic-type attack'],
  [/\bataque de tipo Tierra\b/gi, 'Ground-type attack'],
  [/\bataque de tipo Agua\b/gi, 'Water-type attack'],
  [/\bataque de tipo Fuego\b/gi, 'Fire-type attack'],
  [/\bataque de tipo Fantasma\b/gi, 'Ghost-type attack'],
  [/\bataque\b/gi, 'attack'],
  [/\bataques\b/gi, 'attacks'],
  [/\btipo Tierra\b/gi, 'Ground-type'],
  [/\btipo Agua\b/gi, 'Water-type'],
  [/\btipo Fuego\b/gi, 'Fire-type'],
  [/\btipo Ps[ií]quico\b/gi, 'Psychic-type'],
  [/\btipo Fantasma\b/gi, 'Ghost-type'],
  [/\btipo Drag[oó]n\b/gi, 'Dragon-type'],
  [/\bataques s[uú]per efectivos\b/gi, 'super-effective attacks'],
  [/\brival\b/gi, 'opponent'],
  [/\bobjeto\b/gi, 'item'],
  [/\bmovimientos\b/gi, 'moves'],
  [/\bmovimiento\b/gi, 'move'],
  [/\bamenaza\b/gi, 'threat'],
  [/\bda Revival Herb a\b/gi, 'use Revival Herb on'],
  [/\bda\b/gi, 'use'],
  [/\buna Small Medicine\b/gi, 'one Small Medicine'],
  [/\bTeselia\b/g, 'Unova'],
]

const pivotCleanup: Array<[RegExp, string]> = [
  [/\b[Ss]acrifice ([A-Z][A-Za-z0-9♀♂'’.-]+) and bring in/g, '$1 enters as a pivot, then bring in'],
  [/\b[Ss]acrifice ([A-Z][A-Za-z0-9♀♂'’.-]+) to take/g, '$1 enters as a pivot to take'],
  [/\b[Ss]acrifice ([A-Z][A-Za-z0-9♀♂'’.-]+)/g, '$1 enters as a pivot'],
  [/\b[Ss]end in ([A-Z][A-Za-z0-9♀♂'’.-]+) as a pivot and bring in/g, 'Send in $1 as a pivot, then bring in'],
  [/\bsend in ([A-Z][A-Za-z0-9♀♂'’.-]+) as a pivot and bring in/g, 'send in $1 as a pivot, then bring in'],
  [/\b[Ss]end in ([A-Z][A-Za-z0-9♀♂'’.-]+) and use it as a pivot/g, 'Send in $1 as a pivot'],
  [/\bsend in ([A-Z][A-Za-z0-9♀♂'’.-]+) and use it as a pivot/g, 'send in $1 as a pivot'],
  [/\b[Ll]et ([A-Z][A-Za-z0-9♀♂'’.-]+) faint/g, '$1 enters as a pivot'],
  [/\blet it faint so ([A-Z][A-Za-z0-9♀♂'’.-]+) can enter safely/g, 'use it as a pivot so $1 can enter safely'],
  [/\blet it faint/g, 'use it as a pivot'],
  [/\bdeja que ([A-Z][A-Za-z0-9♀♂'’.-]+) quede debilitado\b/gi, '$1 enters as a pivot'],
  [/\bdeja que ([A-Z][A-Za-z0-9♀♂'’.-]+) caiga\b/gi, '$1 enters as a pivot'],
  [/\bdeja que caiga\b/gi, 'use it as a pivot'],
]

const grammarCleanup: Array<[RegExp, string]> = [
  [/\bUse Nasty Plot until \+([0-9]+)/g, 'Use Nasty Plot to +$1'],
  [/\buse Nasty Plot until \+([0-9]+)/g, 'use Nasty Plot to +$1'],
  [/\bUse Belly Drum until \+6 Attack/g, 'Use Belly Drum to reach +6 Attack'],
  [/\buse Belly Drum until \+6 Attack/g, 'use Belly Drum to reach +6 Attack'],
  [/\bUse Quiver Dance x([0-9]+)/g, 'Use Quiver Dance x$1'],
  [/\buse Quiver Dance x([0-9]+)/g, 'use Quiver Dance x$1'],
  [/\bto reach \+([0-9]+) Speed Speed\b/g, 'to reach +$1 Speed'],
  [/\bto reach \+([0-9]+) Attack Attack\b/g, 'to reach +$1 Attack'],
  [/\bto reach \+([0-9]+) Special attack\b/g, 'to reach +$1 Special Attack'],
  [/\bto reach \+([0-9]+) Special Attack Special Attack\b/g, 'to reach +$1 Special Attack'],
  [/\bbring in with\b/gi, 'bring in'],
  [/\bBring in with\b/g, 'Bring in'],
  [/\bSwitch to with\b/g, 'Switch to'],
  [/\bswitch to with\b/gi, 'switch to'],
  [/\bUse use\b/g, 'Use'],
  [/\buse use\b/g, 'use'],
  [/\bUse one Small Medicine\b/g, 'Use one Small Medicine'],
  [/\bThen then\b/g, 'Then'],
  [/\bthen then\b/g, 'then'],
  [/\bAfter then\b/g, 'After'],
  [/\bif it comes in after that ([A-Z][A-Za-z0-9♀♂'’.-]+)/gi, 'If $1 comes in after that'],
  [/\bWhen it comes in ([A-Z][A-Za-z0-9♀♂'’.-]+)/gi, 'When $1 comes in'],
  [/\bIf it comes in ([A-Z][A-Za-z0-9♀♂'’.-]+)/gi, 'If $1 comes in'],
  [/\bagainst ([A-Z][A-Za-z0-9♀♂'’.-]+), use\b/gi, 'against $1, use'],
  [/\s+([.,:;])/g, '$1'],
]

export const cleanEnglishStrategyText = (text: string, language: Language) => {
  if (language === 'es') return text

  return [
    ...finalMoveTranslations,
    ...finalItemTranslations,
    ...finalAbilityTranslations,
    ...finalPhraseTranslations,
    ...pivotCleanup,
    ...grammarCleanup,
  ].reduce((currentText, [pattern, replacement]) => currentText.replace(pattern, replacement), text)
}
