import type { Language } from '../i18n/translations'

const hybridPhraseCleanup: Array<[RegExp, string]> = [
  [/\bLuego\b/g, 'Then'],
  [/\bluego\b/gi, 'then'],
  [/\bDespu[eé]s\b/g, 'Then'],
  [/\bdespu[eé]s\b/gi, 'then'],
  [/\bCuando\b/g, 'When'],
  [/\bcuando\b/gi, 'when'],
  [/\bSi\b/g, 'If'],
  [/\bsi\b/gi, 'if'],
  [/\bcomo pivote\b/gi, 'as a pivot'],
  [/\bcomo safe pivot\b/gi, 'as a safe pivot'],
  [/\bpara darle entrada segura a ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/gi, 'so $1 can enter safely'],
  [/\bpara dar entrada segura a ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/gi, 'so $1 can enter safely'],
  [/\bpara usar\b/gi, 'to use'],
  [/\bpara use\b/gi, 'to use'],
  [/\bpara entrar seguro\b/gi, 'to enter safely'],
  [/\bpara entrar segura\b/gi, 'to enter safely'],
  [/\bpara quedar en\b/gi, 'to reach'],
  [/\bpara quedar\b/gi, 'to reach'],
  [/\bhasta \+([0-9]+) Attack\b/gi, 'to reach +$1 Attack'],
  [/\bhasta \+([0-9]+) Special Attack\b/gi, 'to reach +$1 Special Attack'],
  [/\bhasta \+([0-9]+) Speed\b/gi, 'to reach +$1 Speed'],
  [/\bBelly Drum to \+6 Attack\b/g, 'Belly Drum to reach +6 Attack'],
  [/\bNasty Plot to \+([0-9]+)\b/g, 'Nasty Plot to +$1'],
  [/\bQuiver Dance to \+([0-9]+)\b/g, 'Quiver Dance to +$1'],
  [/\by bring in\b/gi, 'and bring in'],
  [/\bo bring in\b/gi, 'or bring in'],
  [/\by switch to\b/gi, 'and switch to'],
  [/\bo switch to\b/gi, 'or switch to'],
  [/\by use\b/gi, 'and use'],
  [/\bo use\b/gi, 'or use'],
  [/\by luego\b/gi, 'and then'],
  [/\bo luego\b/gi, 'or then'],
  [/\bentra con\b/gi, 'bring in'],
  [/\bentra\b/gi, 'comes in'],
  [/\bsale\b/gi, 'comes in'],
  [/\busa\b/gi, 'use'],
  [/\busando\b/gi, 'using'],
  [/\butiliza\b/gi, 'uses'],
  [/\bcambia a\b/gi, 'switch to'],
  [/\bsaca a\b/gi, 'send in'],
  [/\bsacrifica a\b/gi, 'send in'],
  [/\bdeja que\b/gi, 'let'],
  [/\bcaiga\b/gi, 'act as a pivot'],
  [/\bquede debilitado\b/gi, 'gets knocked out'],
  [/\bquede debilitada\b/gi, 'gets knocked out'],
  [/\bdebilitado\b/gi, 'knocked out'],
  [/\bdebilitada\b/gi, 'knocked out'],
  [/\bfrente a\b/gi, 'against'],
  [/\bcontra\b/gi, 'against'],
  [/\brival\b/gi, 'opponent'],
  [/\bobjeto\b/gi, 'item'],
  [/\bmovimiento\b/gi, 'move'],
  [/\bmovimientos\b/gi, 'moves'],
  [/\bamenaza\b/gi, 'threat'],
  [/\bruta\b/gi, 'route'],
  [/\bcontin[uú]a\b/gi, 'continue'],
  [/\brevisa\b/gi, 'check'],
  [/\bespera\b/gi, 'wait'],
  [/\bcr[ií]tico\b/gi, 'critical hit'],
]

const hybridSentenceCleanup: Array<[RegExp, string]> = [
  [/\bThen bring in Politoed as a pivot and bring in Poliwrath 🐸🥊 to use Belly Drum to reach \+6 Attack\b/g, 'Then send in Politoed as a pivot, then bring in Poliwrath 🐸🥊 to use Belly Drum and reach +6 Attack'],
  [/\bbring in Politoed as a pivot and bring in Poliwrath 🐸🥊 to use Belly Drum to reach \+6 Attack\b/gi, 'send in Politoed as a pivot, then bring in Poliwrath 🐸🥊 to use Belly Drum and reach +6 Attack'],
  [/\bThen bring in Politoed as a pivot and bring in Poliwrath to use Belly Drum to reach \+6 Attack\b/g, 'Then send in Politoed as a pivot, then bring in Poliwrath to use Belly Drum and reach +6 Attack'],
  [/\bbring in Politoed as a pivot and bring in Poliwrath to use Belly Drum to reach \+6 Attack\b/gi, 'send in Politoed as a pivot, then bring in Poliwrath to use Belly Drum and reach +6 Attack'],
  [/\bSend in Politoed as a pivot and bring in Poliwrath 🐸🥊 to use Belly Drum to reach \+6 Attack\b/g, 'Send in Politoed as a pivot, then bring in Poliwrath 🐸🥊 to use Belly Drum and reach +6 Attack'],
  [/\bsend in Politoed as a pivot and bring in Poliwrath 🐸🥊 to use Belly Drum to reach \+6 Attack\b/g, 'send in Politoed as a pivot, then bring in Poliwrath 🐸🥊 to use Belly Drum and reach +6 Attack'],
]

const grammarCleanup: Array<[RegExp, string]> = [
  [/\bto use Belly Drum to reach \+6 Attack\b/g, 'to use Belly Drum and reach +6 Attack'],
  [/\buse Belly Drum to \+6 Attack\b/gi, 'use Belly Drum to reach +6 Attack'],
  [/\buse Belly Drum to reach \+6 Attack\b/gi, 'use Belly Drum to reach +6 Attack'],
  [/\bbring in ([A-Z][A-Za-z0-9♀♂'’.-]+) as a pivot\b/g, 'send in $1 as a pivot'],
  [/\bBring in ([A-Z][A-Za-z0-9♀♂'’.-]+) as a pivot\b/g, 'Send in $1 as a pivot'],
  [/\bthen then\b/gi, 'then'],
  [/\bThen then\b/g, 'Then'],
  [/\band and\b/gi, 'and'],
  [/\bor or\b/gi, 'or'],
  [/\bIf it comes in ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/g, 'If $1 comes in'],
  [/\bWhen it comes in ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/g, 'When $1 comes in'],
  [/\bIf comes in ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/g, 'If $1 comes in'],
  [/\bWhen comes in ([A-Z][A-Za-z0-9♀♂'’.-]+)\b/g, 'When $1 comes in'],
  [/\s+([.,:;])/g, '$1'],
  [/\s{2,}/g, ' '],
]

export const cleanHybridEnglishStrategyText = (text: string, language: Language) => {
  if (language === 'es') return text

  return [
    ...hybridPhraseCleanup,
    ...hybridSentenceCleanup,
    ...grammarCleanup,
  ].reduce((currentText, [pattern, replacement]) => currentText.replace(pattern, replacement), text).trim()
}
