import type { Language } from '../i18n/translations'

const exactTranslations: Record<string, string> = {
  '🪨 Trampa Rocas 🪨': '🪨 Stealth Rock 🪨',
  'TRAMPA ROCAS': 'STEALTH ROCK',
  '🐌 Cambia a Slowbro': '🐌 Switch to Slowbro',
  'Cambia a Slowbro': 'Switch to Slowbro',
  'Gengar + Otra Vez': 'Gengar + Encore',
  '👀': '👀',
  'En la base de datos no se ha registrado que Lorelei inicie con este Pokémon.': 'Lorelei has not been recorded starting with this Pokémon in the database.',
  'Coloca Trampa Rocas frente a Lucario. Cuando entre Lapras, cambia a Slowbro y usa Bostezo.': 'Set up Stealth Rock against Lucario. When Lapras comes in, switch to Slowbro and use Yawn.',
  'Después saca a Politoed y deja que caiga para darle entrada segura a Poliwrath.': 'Then send out Politoed and let it faint so Poliwrath can enter safely.',
  'Con Poliwrath en campo, usa Tambor para quedar en +6 Ataque y comienza a barrer. 🐸': 'With Poliwrath on the field, use Belly Drum to reach +6 Attack and start sweeping. 🐸',
  'Coloca Trampa Rocas y revisa qué hace Bronzong antes de elegir la ruta.': 'Set up Stealth Rock and check what Bronzong does before choosing the route.',
  'Si Bronzong se queda en campo, revisa su movimiento.': 'If Bronzong stays in, check its move.',
  'Si usa Giro Bola, cambia a Volcarona, usa Especial X y barre con ataques súper efectivos. 🔔 Si Bronzong se quema, puedes usar Danza Aleteo x2 antes de atacar.': 'If it uses Gyro Ball, switch to Volcarona, use X Sp. Atk, and sweep with super-effective attacks. 🔔 If Bronzong gets burned, you can use Quiver Dance x2 before attacking.',
  'Si usa Autodestrucción y entra Chansey, saca a Politoed y deja que caiga. Luego entra Poliwrath, usa Tambor para quedar en +6 Ataque y barre.': 'If it uses Self-Destruct and Chansey comes in, send out Politoed and let it faint. Then bring in Poliwrath, use Belly Drum to reach +6 Attack, and sweep.',
  'Si usa Cabezazo Zen o Terremoto, cambia a Slowbro. Frente a Nidoking, usa Bostezo, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If it uses Zen Headbutt or Earthquake, switch to Slowbro. Against Nidoking, use Yawn, sacrifice Politoed, then bring in Poliwrath and use Belly Drum to reach +6 Attack.',
  'Si usa Autodestrucción y entra Nidoking, usa Amortiguador con Chansey hasta quedar con PS al máximo.': 'If it uses Self-Destruct and Nidoking comes in, use Soft-Boiled with Chansey until she is at full HP.',
  'Si después de curarte el rival se queda, usa Teletransporte. Entra Slowbro, usa Bostezo, sacrifica a Politoed y termina con Poliwrath usando Tambor hasta +6 Ataque.': 'If the opponent stays in after you heal, use Teleport. Bring in Slowbro, use Yawn, sacrifice Politoed, and finish with Poliwrath using Belly Drum to reach +6 Attack.',
  'Si cambia a Chansey, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If it switches to Chansey, sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.',
  'Si entra Hariyama, revisa su objeto antes de decidir.': 'If Hariyama comes in, check its item before choosing the route.',
  'Si tiene Llamasfera, cambia a Slowbro. Luego cambia a Gengar, usa Otra Vez, Maquinación hasta +4 y Velocidad X para quedar en +2 Velocidad. 🔔 Barre con Bola Sombra.': 'If it has Flame Orb, switch to Slowbro. Then switch to Gengar, use Encore, use Nasty Plot to +4, and use X Speed to reach +2 Speed. 🔔 Sweep with Shadow Ball.',
  'Si no tiene Llamasfera, cambia a Slowbro y usa Bostezo. Sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque. 🔔 Usa Puño Drenaje contra Jynx.': 'If it does not have Flame Orb, switch to Slowbro and use Yawn. Sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack. 🔔 Use Drain Punch against Jynx.',
  'Si entra Walrein o Dewgong, usa la ruta de Gengar con Otra Vez.': 'If Walrein or Dewgong comes in, use the Gengar route with Encore.',
  'Entra con Gengar, usa Otra Vez y luego Maquinación hasta +2.': 'Bring in Gengar, use Encore, then use Nasty Plot to +2.',
  'Si el rival se queda encerrado, sube con Maquinación hasta +6. 🔔 Barre con Bola Sombra.': 'If the opponent stays locked in, boost with Nasty Plot up to +6. 🔔 Sweep with Shadow Ball.',
  'Si cambia a Lapras, sigue atacando hasta llegar a Bronzong. Frente a Bronzong, entra Volcarona y usa Danza Aleteo x1 antes de barrer.': 'If it switches to Lapras, keep attacking until Bronzong comes in. Against Bronzong, bring in Volcarona and use Quiver Dance x1 before sweeping.',
  'Si entra Lucario, usa la ruta de Gengar.': 'If Lucario comes in, use the Gengar route.',
  'Cambia a Gengar, usa Otra Vez, Maquinación hasta +4 y Velocidad X para quedar en +2 Velocidad. 🔔 Barre con Bola Sombra.': 'Switch to Gengar, use Encore, use Nasty Plot to +4, and use X Speed to reach +2 Speed. 🔔 Sweep with Shadow Ball.',
  'Coloca Trampa Rocas frente a Bronzong y luego usa Encanto para bajar su Ataque. ❤️': 'Set up Stealth Rock against Bronzong, then use Charm to lower its Attack. ❤️',
  'Si Bronzong usa Cabezazo Zen o Terremoto, cambia a Slowbro. Frente a Nidoking, usa Bostezo, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If Bronzong uses Zen Headbutt or Earthquake, switch to Slowbro. Against Nidoking, use Yawn, sacrifice Politoed, then bring in Poliwrath and use Belly Drum to reach +6 Attack.',
  'Si usa Autodestrucción y entra Chansey, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If it uses Self-Destruct and Chansey comes in, sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.',
  'Si usa Autodestrucción y entra Nidoking, usa Amortiguador hasta recuperar los PS al máximo.': 'If it uses Self-Destruct and Nidoking comes in, use Soft-Boiled until Chansey recovers to full HP.',
  'Coloca Trampa Rocas. 🔔 Si Exeggutor no cambia, usa Amortiguador para mantener a Chansey sana. 🔔': 'Set up Stealth Rock. 🔔 If Exeggutor does not switch, use Soft-Boiled to keep Chansey healthy. 🔔',
  'Si entra Lapras, cambia a Politoed. Luego cambia a Slowbro cuando salga Mantine.': 'If Lapras comes in, switch to Politoed. Then switch to Slowbro when Mantine comes in.',
  'Con Slowbro frente a Mantine, usa Bostezo. Cuando salga Magnezone, sacrifica a Poliwrath para darle entrada segura a Volcarona.': 'With Slowbro against Mantine, use Yawn. When Magnezone comes in, sacrifice Poliwrath so Volcarona can enter safely.',
  'Con Volcarona, usa Danza Aleteo x1 y Especial X. 🔔 Usa Psíquico contra Mantine. 🔔': 'With Volcarona, use Quiver Dance x1 and X Sp. Atk. 🔔 Use Psychic against Mantine. 🔔',
  'Si entra Golduck, cambia a Gengar.': 'If Golduck comes in, switch to Gengar.',
  'Si Golduck se queda, cambia a Slowbro cuando salga Mantine. Usa Bostezo frente a Magnezone, sacrifica a Poliwrath y entra con Volcarona.': 'If Golduck stays in, switch to Slowbro when Mantine comes in. Use Yawn against Magnezone, sacrifice Poliwrath, then bring in Volcarona.',
  'Si entra Lapras directamente, cambia a Slowbro y usa Bostezo frente a Magnezone.': 'If Lapras comes in directly, switch to Slowbro and use Yawn against Magnezone.',
  'Sacrifica a Poliwrath y entra con Volcarona. Usa Danza Aleteo x2 y Especial X. 🔔 Usa Psíquico contra Mantine. 🔔': 'Sacrifice Poliwrath and bring in Volcarona. Use Quiver Dance x2 and X Sp. Atk. 🔔 Use Psychic against Mantine. 🔔',
  'Coloca Trampa Rocas y cambia a Gengar.': 'Set up Stealth Rock and switch to Gengar.',
  'Luego cambia a Slowbro cuando entre Mantine. Usa Bostezo frente a Magnezone y sacrifica a Poliwrath para darle entrada segura a Volcarona.': 'Then switch to Slowbro when Mantine comes in. Use Yawn against Magnezone and sacrifice Poliwrath so Volcarona can enter safely.',
  'Después de Mantine, usa Revivir Hierba en Poliwrath, una Medicina Pequeña y continúa la ruta.': 'After Mantine, use a Revival Herb on Poliwrath, use a Small Medicine, and continue the route.',
  'Cambia a Slowbro y usa Bostezo para dormir la amenaza.': 'Switch to Slowbro and use Yawn to put the threat to sleep.',
  'Con Poliwrath, usa Tambor para quedar en +6 Ataque. 🐸 Usa Puño Drenaje contra Jynx.': 'With Poliwrath, use Belly Drum to reach +6 Attack. 🐸 Use Drain Punch against Jynx.',
  'Cambia a Slowbro. Cuando salga Hariyama, usa Bostezo.': 'Switch to Slowbro. When Hariyama comes in, use Yawn.',
  'Coloca Trampa Rocas. Si Lapras se queda en campo, revisa su movimiento.': 'Set up Stealth Rock. If Lapras stays in, check its move.',
  'Si usa Rayo Hielo, sacrifica a Politoed. Luego entra con Poliwrath, usa Tambor para quedar en +6 Ataque y usa Cascada contra Banette. 🔔 Si un Rayo Hielo crítico debilita a Poliwrath, cambia de estrategia. 🔔': 'If it uses Ice Beam, sacrifice Politoed. Then bring in Poliwrath, use Belly Drum to reach +6 Attack, and use Waterfall against Banette. 🔔 If a critical Ice Beam knocks out Poliwrath, switch to another strategy. 🔔',
  'Si usa Acua Cola, cambia a Politoed. Luego cambia a Slowbro y espera a Mantine. Usa Bostezo frente a Magnezone, sacrifica a Poliwrath y entra con Volcarona.': 'If it uses Aqua Tail, switch to Politoed. Then switch to Slowbro and wait for Mantine. Use Yawn against Magnezone, sacrifice Poliwrath, and bring in Volcarona.',
  'Si Golduck se queda, cambia a Slowbro y espera a Mantine. Usa Bostezo frente a Magnezone, sacrifica a Poliwrath y entra con Volcarona.': 'If Golduck stays in, switch to Slowbro and wait for Mantine. Use Yawn against Magnezone, sacrifice Poliwrath, and bring in Volcarona.',
  'Con Volcarona, usa Danza Aleteo x1 y Especial X. 🔔 Usa Psíquico contra Mantine, da Revivir Hierba a Poliwrath, usa una Medicina Pequeña y continúa. 🔔': 'With Volcarona, use Quiver Dance x1 and X Sp. Atk. 🔔 Use Psychic against Mantine, use a Revival Herb on Poliwrath, use a Small Medicine, and continue. 🔔',
  'Si entra Lapras, cambia a Slowbro y usa Bostezo frente a Magnezone.': 'If Lapras comes in, switch to Slowbro and use Yawn against Magnezone.',
  'Sacrifica a Poliwrath y entra con Volcarona. Usa Danza Aleteo x2 y Especial X. 🔔 Usa Psíquico contra Mantine, da Revivir Hierba a Poliwrath, usa una Medicina Pequeña y continúa. 🔔': 'Sacrifice Poliwrath and bring in Volcarona. Use Quiver Dance x2 and X Sp. Atk. 🔔 Use Psychic against Mantine, use a Revival Herb on Poliwrath, use a Small Medicine, and continue. 🔔',
  'Si entra Hariyama, cambia a Slowbro y usa Bostezo.': 'If Hariyama comes in, switch to Slowbro and use Yawn.',
  'Si después entra Nidoking, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque. 🔔 Usa Puño Drenaje contra Jynx. 🔔': 'If Nidoking comes in after that, sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack. 🔔 Use Drain Punch against Jynx. 🔔',
  'Si después entra Jynx, entra con Volcarona y usa Danza Aleteo x2.': 'If Jynx comes in after that, bring in Volcarona and use Quiver Dance x2.',
  'Si entra Lucario, elige la ruta según su objeto.': 'If Lucario comes in, choose the route based on its item.',
  'Ruta rápida: usa Teletransporte para revisar el objeto.': 'Fast route: use Teleport to check the item.',
  'Si tiene Vidasfera, entra con Gengar, usa Otra Vez, Maquinación hasta +4 y Velocidad X para quedar en +2 Velocidad. Barre con Bola Sombra.': 'If it has Life Orb, bring in Gengar, use Encore, use Nasty Plot to +4, and use X Speed to reach +2 Speed. Sweep with Shadow Ball.',
  'Si no tiene Vidasfera, envía a Slowbro y usa Bostezo frente a Lapras. Luego sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If it does not have Life Orb, send in Slowbro and use Yawn against Lapras. Then sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.',
  'Si quieres ahorrar dinero, entra con Gengar, usa Otra Vez y Maquinación hasta +2. Si Lucario se queda, sube con Maquinación hasta +4 y usa Velocidad X para quedar en +2 Velocidad. Barre con Bola Sombra.': 'If you want to save money, bring in Gengar, use Encore, and use Nasty Plot to +2. If Lucario stays in, boost with Nasty Plot to +4 and use X Speed to reach +2 Speed. Sweep with Shadow Ball.',
  'Si entra Mantine, cambia a Chansey y usa Amortiguador frente a Lucario.': 'If Mantine comes in, switch to Chansey and use Soft-Boiled against Lucario.',
  'Luego entra con Gengar, usa Maquinación hasta +4 y Velocidad X para quedar en +2 Velocidad. 🔔 Barre con Bola Sombra. 🔔': 'Then bring in Gengar, use Nasty Plot to +4, and use X Speed to reach +2 Speed. 🔔 Sweep with Shadow Ball. 🔔',
  'Si entra Bronzong, usa Encanto con Chansey.': 'If Bronzong comes in, use Charm with Chansey.',
  'Si usa un ataque Psíquico o de tipo Tierra, cambia a Slowbro y usa Bostezo frente a Nidoking. Luego sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If it uses a Psychic-type or Ground-type attack, switch to Slowbro and use Yawn against Nidoking. Then sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.',
  'Si Bronzong se queda, usa Teletransporte. Entra Slowbro, usa Bostezo, sacrifica a Politoed y termina con Poliwrath usando Tambor hasta +6 Ataque.': 'If Bronzong stays in, use Teleport. Bring in Slowbro, use Yawn, sacrifice Politoed, and finish with Poliwrath using Belly Drum to reach +6 Attack.',
  'Entra con Gengar, usa Otra Vez y luego cambia a Slowbro para revisar el objeto de Lucario.': 'Bring in Gengar, use Encore, then switch to Slowbro to check Lucario’s item.',
  'Si tiene Vidasfera, cambia a Chansey. Cuando salga Lapras, coloca Trampa Rocas. Cuando vuelva Lucario, cambia a Slowbro y usa Bostezo.': 'If it has Life Orb, switch to Chansey. When Lapras comes in, set up Stealth Rock. When Lucario comes back in, switch to Slowbro and use Yawn.',
  'Si Lucario se queda, usa Teletransporte hacia Volcarona. Usa Danza Aleteo x1, derrótalo y cuando salga Dragonite usa Especial X. Mantén los PS sobre 35%.': 'If Lucario stays in, use Teleport into Volcarona. Use Quiver Dance x1, knock it out, and when Dragonite comes in, use X Sp. Atk. Keep HP above 35%.',
  'Si después sale Lapras, usa Volcarona con Danza Aleteo x2. Mantén los PS sobre 46%.': 'If Lapras comes in after that, use Volcarona with Quiver Dance x2. Keep HP above 46%.',
  'Si no tiene Vidasfera, cambia a Chansey y coloca Trampa Rocas. Luego cambia a Slowbro y usa Bostezo. Cuando salga Lapras, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If it does not have Life Orb, switch to Chansey and set up Stealth Rock. Then switch to Slowbro and use Yawn. When Lapras comes in, sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.',
  'Coloca Trampa Rocas y mantén Amortiguador hasta que el rival cambie.': 'Set up Stealth Rock and keep using Soft-Boiled until the opponent switches.',
  'Si Golduck se queda, cambia a Slowbro. Cuando salga Mantine, usa Bostezo. Frente a Magnezone, sacrifica a Poliwrath y entra con Volcarona.': 'If Golduck stays in, switch to Slowbro. When Mantine comes in, use Yawn. Against Magnezone, sacrifice Poliwrath and bring in Volcarona.',
  'Si entra Lapras, cambia a Poliwrath y luego cambia a Slowbro. Cuando salga Mantine, usa Bostezo.': 'If Lapras comes in, switch to Poliwrath and then switch to Slowbro. When Mantine comes in, use Yawn.',
  'Cuando salga Magnezone, sacrifica a Poliwrath y entra con Volcarona. Usa Danza Aleteo x1 y Especial X.': 'When Magnezone comes in, sacrifice Poliwrath and bring in Volcarona. Use Quiver Dance x1 and X Sp. Atk.',
  'Si entra Lucario, cambia a Slowbro y usa Bostezo.': 'If Lucario comes in, switch to Slowbro and use Yawn.',
  'Después saca a Politoed y deja que caiga. Entra con Poliwrath y usa Tambor hasta +6 Ataque.': 'Then send out Politoed and let it faint. Bring in Poliwrath and use Belly Drum to reach +6 Attack.',
  'Si Bronzong usa un ataque Psíquico o de tipo Tierra, cambia a Slowbro y usa Bostezo. Luego sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If Bronzong uses a Psychic-type or Ground-type attack, switch to Slowbro and use Yawn. Then sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.',
  'Si usa Explosión y entra Chansey, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If it uses Explosion and Chansey comes in, sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.',
  'Si usa Explosión y entra Nidoking, usa Amortiguador con Chansey hasta quedar con PS al máximo.': 'If it uses Explosion and Nidoking comes in, use Soft-Boiled with Chansey until she is at full HP.',
  'Si Bronzong se queda, usa Teletransporte hacia Slowbro. Usa Bostezo, sacrifica a Politoed y termina con Poliwrath usando Tambor hasta +6 Ataque.': 'If Bronzong stays in, use Teleport into Slowbro. Use Yawn, sacrifice Politoed, and finish with Poliwrath using Belly Drum to reach +6 Attack.',
  'Con Volcarona, usa Danza Aleteo x1 y Especial X.': 'With Volcarona, use Quiver Dance x1 and X Sp. Atk.',
  'Si entra Lapras después de Golduck, cambia a Slowbro y usa Bostezo frente a Magnezone.': 'If Lapras comes in after Golduck, switch to Slowbro and use Yawn against Magnezone.',
  'Sacrifica a Poliwrath y entra con Volcarona. Usa Danza Aleteo x2 y Especial X.': 'Sacrifice Poliwrath and bring in Volcarona. Use Quiver Dance x2 and X Sp. Atk.',
  'Si entra Nidoking, saca a Politoed y deja que caiga. Luego entra con Poliwrath y usa Tambor hasta +6 Ataque. 🔔 Usa Piel Seca contra Jynx. 🔔': 'If Nidoking comes in, send out Politoed and let it faint. Then bring in Poliwrath and use Belly Drum to reach +6 Attack. 🔔 Use Dry Skin against Jynx. 🔔',
  'Si entra Jynx, entra con Volcarona y usa Danza Aleteo x3.': 'If Jynx comes in, bring in Volcarona and use Quiver Dance x3.',
  'Coloca Trampa Rocas. Cuando salga Lucario, cambia a Gengar.': 'Set up Stealth Rock. When Lucario comes in, switch to Gengar.',
  'Con Gengar, usa Otra Vez, Maquinación hasta +4 y Velocidad X para quedar en +2 Velocidad.': 'With Gengar, use Encore, use Nasty Plot to +4, and use X Speed to reach +2 Speed.',
  'Mantén Otra Vez cada vez que puedas para controlar al rival. Cuando Gengar esté listo, barre con Bola Sombra.': 'Keep using Encore whenever possible to control the opponent. When Gengar is ready, sweep with Shadow Ball.',
  'Sale Lucario → cambia a Gengar, usa Otra Vez, usa Maquinación hasta +4 y luego usa Velocidad X para quedar +2 Velocidad.': 'Lucario comes in → switch to Gengar, use Encore, use Nasty Plot to +4, then use X Speed to reach +2 Speed.',
  'Mantén Otra Vez cada vez que puedas para controlar al rival.': 'Keep using Encore whenever possible to control the opponent.',
  'Cuando Gengar esté listo, barre con Bola Sombra.': 'When Gengar is ready, sweep with Shadow Ball.',
  '🔔 Usa Piel Seca contra Jynx. 🔔': '🔔 Use Dry Skin against Jynx. 🔔',
  'Coloca Trampa Rocas. Cuando salga Bronzong, usa Encanto con Chansey.': 'Set up Stealth Rock. When Bronzong comes in, use Charm with Chansey.',
  'Si Bronzong usa un ataque Psíquico o Terremoto, cambia a Slowbro y usa Bostezo. Cuando salga Nidoking, sacrifica a Politoed y entra con Poliwrath para usar Tambor hasta +6 Ataque.': 'If Bronzong uses a Psychic-type attack or Earthquake, switch to Slowbro and use Yawn. When Nidoking comes in, sacrifice Politoed and bring in Poliwrath to use Belly Drum and reach +6 Attack.'
}

const moveTranslations: Array<[RegExp, string]> = [
  [/\bTRUCO\b/gi, 'Trick'],
  [/\bTruco\b/g, 'Trick'],
  [/\bTRAMPA ROCAS\b/gi, 'Stealth Rock'],
  [/\bTrampa Rocas\b/gi, 'Stealth Rock'],
  [/\bOTRA VEZ\b/gi, 'Encore'],
  [/\bOtra vez\b/gi, 'Encore'],
  [/\bMaquinaci[oó]n\b/gi, 'Nasty Plot'],
  [/\bTambor\b/gi, 'Belly Drum'],
  [/\bDanza Aleteo\b/gi, 'Quiver Dance'],
  [/\bVelocidad X\b/gi, 'X Speed'],
  [/\bPrecisi[oó]n X\b/gi, 'X Accuracy'],
  [/\bEspecial X\b/gi, 'X Sp. Atk'],
  [/\bSurf\b/gi, 'Surf'],
  [/\bCar[aá]mbano\b/gi, 'Icicle Spear'],
  [/\bRoca Afilada\b/gi, 'Stone Edge'],
  [/\bTriturar\b/gi, 'Crunch'],
  [/\bTerremoto\b/gi, 'Earthquake'],
  [/\bCabezazo Zen\b/gi, 'Zen Headbutt'],
  [/\bGiro Bola\b/gi, 'Gyro Ball'],
  [/\bAutodestrucci[oó]n\b/gi, 'Self-Destruct'],
  [/\bExplosi[oó]n\b/gi, 'Explosion'],
  [/\bHuesomerang\b/gi, 'Bonemerang'],
  [/\bEscaldar\b/gi, 'Scald'],
  [/\bRayo Hielo\b/gi, 'Ice Beam'],
  [/\bRayo\b/gi, 'Thunderbolt'],
  [/\bAcua Cola\b/gi, 'Aqua Tail'],
  [/\bCascada\b/gi, 'Waterfall'],
  [/\bPoder Oculto\b/gi, 'Hidden Power'],
  [/\bBostezo\b/gi, 'Yawn'],
  [/\bAmortiguador\b/gi, 'Soft-Boiled'],
  [/\bTeletransporte\b/gi, 'Teleport'],
  [/\bPuño Drenaje\b/gi, 'Drain Punch'],
  [/\bBola Sombra\b/gi, 'Shadow Ball'],
  [/\bEncanto\b/gi, 'Charm'],
  [/\bPs[ií]quico\b/gi, 'Psychic'],
]

const itemTranslations: Array<[RegExp, string]> = [
  [/\bLlamasfera\b/gi, 'Flame Orb'],
  [/\bVidasfera\b/gi, 'Life Orb'],
  [/\bRevivir Hierba\b/gi, 'Revival Herb'],
  [/\bMedicina Pequeña\b/gi, 'Small Medicine'],
]

const abilityTranslations: Array<[RegExp, string]> = [
  [/\bPiel Seca\b/gi, 'Dry Skin'],
]

const phraseTranslations: Array<[RegExp, string]> = [
  [/\bNO CAMBIA\b/g, 'DOES NOT SWITCH'],
  [/\bNo cambia\b/g, 'Does not switch'],
  [/\bSi utiliza\b/gi, 'If it uses'],
  [/\bSi usa\b/gi, 'If it uses'],
  [/\bSi cambia a\b/gi, 'If it switches to'],
  [/\bSi entra\b/gi, 'If it comes in'],
  [/\bSi tiene\b/gi, 'If it has'],
  [/\bSi no tiene\b/gi, 'If it does not have'],
  [/\bcambia a\b/gi, 'switch to'],
  [/\bCambia a\b/g, 'Switch to'],
  [/\bsaca a\b/gi, 'send out'],
  [/\bSacrifica a\b/g, 'Sacrifice'],
  [/\bsacrifica a\b/gi, 'sacrifice'],
  [/\bsacrificar a\b/gi, 'sacrifice'],
  [/\bsacrifica\b/gi, 'sacrifice'],
  [/\bdeja que caiga\b/gi, 'let it faint'],
  [/\busa\b/gi, 'use'],
  [/\bUsa\b/g, 'Use'],
  [/\butiliza\b/gi, 'use'],
  [/\bpara quedar en\b/gi, 'to reach'],
  [/\bAtaque Especial\b/gi, 'Special Attack'],
  [/\bAtaque\b/gi, 'Attack'],
  [/\bVelocidad\b/gi, 'Speed'],
  [/\bPS al máximo\b/gi, 'full HP'],
  [/\bPS\b/g, 'HP'],
  [/\bbarrer\b/gi, 'sweep'],
  [/\bbarre\b/gi, 'sweep'],
  [/\bpara luego volver con\b/gi, 'then go back to'],
  [/\bsi a[uú]n sigue en el campo y no cambia\b/gi, 'if it is still on the field and does not switch'],
  [/\bsi sorpresivamente utiliza\b/gi, 'if it unexpectedly uses'],
  [/\bsi .* esta bloqueado usa\b/gi, 'if the locked move is unavailable, use'],
  [/\bencerrar en\b/gi, 'lock into'],
  [/\bcontra\b/gi, 'against'],
  [/\bfrente a\b/gi, 'against'],
  [/\btipo Tierra\b/gi, 'Ground-type'],
]

const regionTranslations: Array<[RegExp, string]> = [
  [/\bTeselia\b/g, 'Unova'],
]

export const translateStrategyText = (text: string, language: Language) => {
  if (language === 'es') return text

  const exactTranslation = exactTranslations[text]

  if (exactTranslation) return exactTranslation

  return [...moveTranslations, ...itemTranslations, ...abilityTranslations, ...phraseTranslations, ...regionTranslations]
    .reduce((currentText, [pattern, replacement]) => currentText.replace(pattern, replacement), text)
}

export const formatStrategyText = (text: string) => {
  return text
    .replace(/\s+/g, ' ')
    .trim()
}
